---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    backstage.io/kubernetes-id: portale-marghe1
    app.kubernetes.io/name: portale-marghe1
    rht-gitops.com/janus-argocd: portale-marghe1
  name: storeuser-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    backstage.io/kubernetes-id: portale-marghe1
    app.kubernetes.io/name: portale-marghe1
    rht-gitops.com/janus-argocd: portale-marghe1
  name: storeuseradmin-sa
