---
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: portale-marghe1-scc-storeuser
  labels:
    backstage.io/kubernetes-id: portale-marghe1
    app.kubernetes.io/name: portale-marghe1
    rht-gitops.com/janus-argocd: portale-marghe1
allowHostPID: false
allowHostNetwork: false
allowPrivilegeEscalation: true
allowHostDirVolumePlugin: false
allowHostIPC: false
readOnlyRootFilesystem: false
allowHostPorts: false
allowPrivilegedContainer: false
runAsUser:
  type: MustRunAs
  uid: 10001
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
  - system:serviceaccount:portale-marghe1:storeuser-sa
---
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: portale-marghe1-scc-storeuseradmin
  annotations:
    backstage.io/kubernetes-id: portale-marghe1
allowHostPID: false
allowHostNetwork: false
allowPrivilegeEscalation: true
allowHostDirVolumePlugin: false
allowHostIPC: false
readOnlyRootFilesystem: false
allowHostPorts: false
allowPrivilegedContainer: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
  - system:serviceaccount:portale-marghe1:storeuseradmin-sa
